language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - mv ../cirici-codesniffer ../cirici_codesniffer && cd ../cirici_codesniffer
  - composer selfupdate
  - composer install

script:
  - vendor/bin/phpunit

notifications:
  email: false
